version: '3'

services:
  db:
    image: mysql:8.0.17
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'restaurant'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: '123456'
       MYSQL_ROOT_PASSWORD: '123456'
    volumes:
        - ./db_restaurante:/restaurant/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
